#!/bin/bash

echo
echo "Command: $(basename $0) $@"

a=$1
b=$2

if [[ $2 !=	"" ]]; then
	b=$2
fi

svg1=$(basename $a | sed "s|from_|sch1-|g")
svg2=$(basename $b | sed "s|to_|sch2-|g")

mv -f "$a" "$svg1"
mv -f "$b" "$svg2"
