#!/bin/bash

# Wrapper for plotgitsh to run it in the right folder

ARGS=
DIRECTORY=
LIBRARY=

while [[ $# -gt 0 ]]
do
	key="$1"

	case $key in

	-d)
		DIRECTORY="$2"
		shift
		shift
		;;

	-l)
		LIBRARY="$1 $2"
		shift
		shift
		;;

	*)
		ARGS="$ARGS$key " 
		shift
		;;
	esac
done

if [[ ! "$DIRECTORY" = "." ]] && [[ ! "$DIRECTORY" = "./" ]]; then
	cd "$DIRECTORY" || exit
	LIBRARY=$(basename "$LIBRARY")
fi

cmd="plotgitsch $LIBRARY $ARGS"
echo $cmd
eval "$cmd"

if [[ ! "$DIRECTORY" = "." ]] && [[ ! "$DIRECTORY" = "./" ]]; then
	mv *.svg ../
	cd - > /dev/null || exit
fi
